name: exercici4
description: Simula el llanÃ§ament de dos daus amb SVG i toast.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7     # per renderitzar SVG
  fluttertoast: ^8.2.1    # per mostrar el Toast

flutter:
  uses-material-design: true

  assets:
    - assets/dice1.svg
    - assets/dice2.svg
    - assets/dice3.svg
    - assets/dice4.svg
    - assets/dice5.svg
    - assets/dice6.svg
